"""add structured report tables

Revision ID: 4949a7c22914
Revises: b22fe1d81657
Create Date: 2026-05-09 14:41:32.054612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4949a7c22914'
down_revision: Union[str, Sequence[str], None] = 'b22fe1d81657'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_loads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('source_file', sa.Text(), nullable=False),
    sa.Column('date_start', sa.Date(), nullable=True),
    sa.Column('date_end', sa.Date(), nullable=True),
    sa.Column('rows_loaded', sa.Integer(), nullable=False),
    sa.Column('loaded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_item_export',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('load_id', sa.Integer(), nullable=False),
    sa.Column('item_ref', sa.Text(), nullable=False),
    sa.Column('device', sa.Text(), nullable=False),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('zip', sa.Text(), nullable=True),
    sa.Column('item_type', sa.Text(), nullable=True),
    sa.Column('item_date', sa.DateTime(), nullable=True),
    sa.Column('card_number', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('slot_code', sa.Text(), nullable=True),
    sa.Column('slot_price', sa.Numeric(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('settle_status', sa.Text(), nullable=True),
    sa.Column('card_id', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['load_id'], ['report_loads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_ref')
    )
    op.create_table('detailed_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('load_id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.Text(), nullable=True),
    sa.Column('device', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('day', sa.Date(), nullable=True),
    sa.Column('trans_type', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['load_id'], ['report_loads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_rollup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('load_id', sa.Integer(), nullable=False),
    sa.Column('customer', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('serial_num', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('trans_type', sa.Text(), nullable=True),
    sa.Column('tran_count', sa.Integer(), nullable=True),
    sa.Column('vend_count', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('currency_code', sa.Text(), nullable=True),
    sa.Column('two_tier_pricing', sa.Numeric(), nullable=True),
    sa.Column('loyalty_discount', sa.Numeric(), nullable=True),
    sa.Column('purchase_discount', sa.Numeric(), nullable=True),
    sa.Column('free_product_discount', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['load_id'], ['report_loads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('raw_transactions')
    op.drop_table('raw_payloads')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_payloads',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('received_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('content_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('raw_body', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('source_ip', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('raw_payloads_pkey'))
    )
    op.create_table('raw_transactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('payload_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('received_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('raw_transactions_pkey'))
    )
    op.drop_table('sales_rollup')
    op.drop_table('detailed_activity')
    op.drop_table('daily_item_export')
    op.drop_table('report_loads')
    # ### end Alembic commands ###
